import {
  Headphones,
  BarChart3,
  FolderKanban,
  ListChecks,
  Users as UsersIcon,
  Settings as SettingsIcon,
  PhoneCall,
  Home,
  HelpCircle,
} from "lucide-react";

// Single source of truth for the restructured admin navigation — both the
// top dropdown bar and the compact icon sidebar render from this list, and
// App.jsx's routes are keyed off the same paths, so the three can never
// drift out of sync.
export const ADMIN_NAV = [
  {
    key: "callcenter",
    label: "Call Center",
    icon: Headphones,
    anyPermission: ["view_agent_monitor", "listen_live", "whisper_agents", "barge_calls", "send_broadcast", "can_view_sms_conversations", "can_view_agent_sms", "can_view_campaign_sms"],
    items: [
      { label: "Agent Monitor", path: "/admin/call-center/agent-monitor" },
      { label: "Live Calls", path: "/admin/call-center/live-calls" },
      { label: "Callbacks", path: "/admin/call-center/callbacks" },
      { label: "Inbound Queue", path: "/admin/call-center/inbound-queue" },
      { label: "Broadcast Message", path: "/admin/call-center/broadcast" },
      { label: "SMS Inbox", path: "/admin/sms-inbox" },
    ],
  },
  {
    key: "reports",
    label: "Reports",
    icon: BarChart3,
    anyPermission: [
      "view_campaign_reports",
      "view_agent_reports",
      "view_conversion_reports",
      "view_duration_reports",
      "export_csv",
      "export_pdf",
      "view_financial_metrics",
      "view_leadlist_performance",
      "listen_recordings",
      "download_recordings",
    ],
    items: [
      { label: "Agent Performance", path: "/admin/reports/agent-performance" },
      { label: "Agent Productivity Logs", path: "/admin/reports/productivity-logs" },
      { label: "Call Logs", path: "/admin/reports/call-logs" },
      { label: "Call Recordings", path: "/admin/reports/call-recordings" },
      { label: "SMS Logs", path: "/admin/reports/sms-logs" },
      { label: "Callback Reports", path: "/admin/reports/callback-reports" },
      { label: "Campaign Reports", path: "/admin/reports/campaign-reports" },
      { label: "Disposition Reports", path: "/admin/reports/disposition-reports" },
      { label: "Custom Reports", path: "/admin/reports/custom-reports" },
      { label: "Exports", path: "/admin/reports/exports" },
      { label: "Admin Activity Log", path: "/admin/reports/activity-log" },
      { label: "Global Reports", path: "/superadmin/dashboard", superAdminOnly: true },
    ],
  },
  {
    key: "campaigns",
    label: "Campaigns",
    icon: FolderKanban,
    anyPermission: ["create_campaigns", "edit_campaigns", "pause_resume_campaigns", "change_dialing_mode", "assign_agents_campaigns", "upload_lead_lists", "manage_dnc", "can_enable_sms", "can_edit_sms_templates", "can_edit_email_templates", "can_enable_email"],
    items: [
      { label: "All Campaigns", path: "/admin/campaigns/all" },
      { label: "Create New Campaign", path: "/admin/campaigns/all?create=1" },
      { label: "Lead Lists", path: "/admin/campaigns/lead-lists" },
      { label: "DNC List", path: "/admin/campaigns/dnc" },
      { label: "Scripts", path: "/admin/campaigns/scripts" },
      { label: "SMS Templates", path: "/admin/campaigns/sms-templates" },
      { label: "Email Templates", path: "/admin/campaigns/email-templates" },
      { label: "Dispositions", path: "/admin/campaigns/dispositions" },
      { label: "Client Calendars", path: "/admin/campaigns/client-calendars" },
      { label: "DID Protection", path: "/admin/campaigns/did-protection" },
    ],
  },
  {
    key: "leads",
    label: "Leads",
    icon: ListChecks,
    anyPermission: ["upload_lead_lists", "manage_dnc", "view_leadlist_performance"],
    items: [
      { label: "Lead Search", path: "/admin/leads/search" },
      { label: "Upload Leads", path: "/admin/leads/upload" },
      { label: "Lead Lists", path: "/admin/leads/lists" },
      { label: "Lead List Health", path: "/admin/leads/health" },
      { label: "Custom Fields", path: "/admin/leads/custom-fields" },
    ],
  },
  {
    key: "users",
    label: "Users",
    icon: UsersIcon,
    adminOnly: true,
    items: [
      { label: "All Users", path: "/admin/users/all" },
      { label: "Add New User", path: "/admin/users/all?add=1" },
      { label: "Role Permissions", path: "/admin/users/permissions" },
      { label: "Active Sessions", path: "/admin/users/sessions" },
      { label: "Login History", path: "/admin/users/login-history" },
    ],
  },
  {
    key: "settings",
    label: "Settings",
    icon: SettingsIcon,
    adminOnly: true,
    items: [
      { label: "General Settings", path: "/admin/settings/general" },
      { label: "Dialer Settings", path: "/admin/settings/dialer" },
      { label: "Phone Numbers", path: "/admin/settings/phone-numbers" },
      { label: "Number Rotation Settings", path: "/admin/settings/number-rotation" },
      { label: "Spam Detection Settings", path: "/admin/settings/spam-detection" },
      { label: "Email Notifications", path: "/admin/settings/email-notifications" },
      { label: "Integrations", path: "/admin/settings/integrations" },
      { label: "Billing", path: "/admin/settings/billing" },
      { label: "Hotkey Management", path: "/admin/settings/hotkeys" },
      { label: "Companies", path: "/admin/settings/companies", superAdminOnly: true },
    ],
  },
  {
    key: "phonesystem",
    label: "Phone System",
    icon: PhoneCall,
    adminOnly: true,
    items: [
      { label: "Phone Numbers", path: "/admin/phone-system/numbers" },
      { label: "Add Number", path: "/admin/phone-system/numbers?add=1" },
      { label: "Number Assignment", path: "/admin/phone-system/assignment" },
      { label: "Call Recording Settings", path: "/admin/phone-system/recording-settings" },
      { label: "Voicemail Settings", path: "/admin/phone-system/voicemail" },
      { label: "IVR Settings", path: "/admin/phone-system/ivr" },
      { label: "DID Management", path: "/admin/phone-system/did-management" },
      { label: "DID Reputation Settings", path: "/admin/phone-system/did-settings" },
    ],
  },
];

export const SIDEBAR_EXTRAS = { home: { label: "Home", icon: Home, path: "/admin/dashboard" }, help: { label: "Help", icon: HelpCircle, path: "/knowledge" } };
